'use client';

import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { api } from '@/lib/api';

// This page is rendered by Puppeteer for PDF generation.
// It must have [data-report-ready] set when fully rendered.

interface ReportData {
  id: string;
  name: string;
  module: string;
  tenant_name: string;
  logo_url: string;
  primary_color: string;
  date_from: string;
  date_to: string;
  generated_by: string;
  generated_at: string;
  run_id: string;
  kpis: { label: string; value: string; change?: string }[];
  sections: ReportSection[];
}

interface ReportSection {
  title: string;
  type: 'table' | 'text' | 'kpis';
  content: any;
}

export default function ReportRenderPage() {
  const { id } = useParams();
  const [report, setReport] = useState<ReportData | null>(null);
  const [ready, setReady] = useState(false);

  useEffect(() => {
    if (!id) return;
    api.reports.renderData(id as string)
      .then(r => {
        setReport(r.data);
        // Small delay to ensure charts render
        setTimeout(() => setReady(true), 500);
      })
      .catch(() => setReady(true));
  }, [id]);

  if (!report) {
    return (
      <div className="min-h-screen bg-white flex items-center justify-center">
        <p className="text-gray-500">Loading report...</p>
      </div>
    );
  }

  const primaryColor = report.primary_color || '#2563EB';

  return (
    <div
      data-report-ready={ready || undefined}
      className="bg-white text-gray-900 font-sans"
      style={{ width: '794px', minHeight: '1123px', fontFamily: 'Inter, sans-serif' }}
    >
      {/* Cover Page */}
      <div style={{ background: `linear-gradient(135deg, #020617, #0F172A)`, minHeight: '300px', padding: '60px 60px 40px' }}>
        {report.logo_url && (
          // eslint-disable-next-line @next/next/no-img-element
          <img src={report.logo_url} alt="Logo" style={{ height: '40px', marginBottom: '40px', objectFit: 'contain' }} />
        )}
        <div style={{ marginBottom: '8px', fontSize: '12px', color: primaryColor, fontWeight: 600, textTransform: 'uppercase', letterSpacing: '1px' }}>
          {report.module}
        </div>
        <h1 style={{ fontSize: '28px', fontWeight: 700, color: '#F1F5F9', marginBottom: '12px', lineHeight: 1.2 }}>{report.name}</h1>
        <p style={{ fontSize: '13px', color: '#94A3B8', marginBottom: '32px' }}>
          {new Date(report.date_from).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })} —{' '}
          {new Date(report.date_to).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
        </p>
        <div style={{ display: 'flex', gap: '32px', fontSize: '12px', color: '#64748B' }}>
          <div><span style={{ color: '#475569' }}>Organization</span><br /><span style={{ color: '#CBD5E1', fontWeight: 500 }}>{report.tenant_name}</span></div>
          <div><span style={{ color: '#475569' }}>Generated By</span><br /><span style={{ color: '#CBD5E1', fontWeight: 500 }}>{report.generated_by}</span></div>
          <div><span style={{ color: '#475569' }}>Generated At</span><br /><span style={{ color: '#CBD5E1', fontWeight: 500 }}>{new Date(report.generated_at).toLocaleString()}</span></div>
        </div>
      </div>

      {/* Report Body */}
      <div style={{ padding: '40px 60px' }}>
        {/* KPI Section */}
        {report.kpis?.length > 0 && (
          <div style={{ marginBottom: '32px' }}>
            <h2 style={{ fontSize: '14px', fontWeight: 700, color: '#0F172A', borderBottom: `2px solid ${primaryColor}`, paddingBottom: '8px', marginBottom: '16px' }}>
              Key Performance Indicators
            </h2>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '12px' }}>
              {report.kpis.map((kpi, i) => (
                <div key={i} style={{ background: '#F8FAFC', border: '1px solid #E2E8F0', borderRadius: '8px', padding: '12px' }}>
                  <p style={{ fontSize: '10px', color: '#94A3B8', marginBottom: '4px', textTransform: 'uppercase', letterSpacing: '0.5px' }}>{kpi.label}</p>
                  <p style={{ fontSize: '18px', fontWeight: 700, color: '#0F172A' }}>{kpi.value}</p>
                  {kpi.change && <p style={{ fontSize: '11px', color: kpi.change.startsWith('+') ? '#10B981' : '#EF4444', marginTop: '2px' }}>{kpi.change}</p>}
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Sections */}
        {report.sections?.map((section, i) => (
          <div key={i} style={{ marginBottom: '28px' }}>
            <h2 style={{ fontSize: '14px', fontWeight: 700, color: '#0F172A', borderBottom: '1px solid #E2E8F0', paddingBottom: '8px', marginBottom: '12px' }}>
              {section.title}
            </h2>

            {section.type === 'text' && (
              <p style={{ fontSize: '12px', color: '#475569', lineHeight: 1.6 }}>{section.content}</p>
            )}

            {section.type === 'table' && Array.isArray(section.content?.rows) && (
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '11px' }}>
                <thead>
                  <tr style={{ background: '#0F172A' }}>
                    {section.content.headers?.map((h: string, j: number) => (
                      <th key={j} style={{ padding: '8px 10px', color: '#F1F5F9', fontWeight: 600, textAlign: 'left', borderBottom: `2px solid ${primaryColor}` }}>{h}</th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {section.content.rows.map((row: string[], j: number) => (
                    <tr key={j} style={{ background: j % 2 === 0 ? '#FFFFFF' : '#F8FAFC' }}>
                      {row.map((cell, k) => (
                        <td key={k} style={{ padding: '7px 10px', color: '#374151', borderBottom: '1px solid #E2E8F0' }}>{cell}</td>
                      ))}
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </div>
        ))}
      </div>

      {/* Audit Footer */}
      <div style={{ padding: '16px 60px', background: '#F8FAFC', borderTop: '1px solid #E2E8F0', marginTop: '40px' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '10px', color: '#94A3B8' }}>
          <span>Report ID: {report.run_id}</span>
          <span>Generated: {new Date(report.generated_at).toISOString()}</span>
          <span>CONFIDENTIAL — {report.tenant_name}</span>
        </div>
      </div>
    </div>
  );
}
