export interface ReportCatalogEntry {
  id: string;
  name: string;
  module: string;
  type: string;
  description: string;
  formats: string[];
  defaultSchedule?: string;
  parameters: string[];
}

export const REPORT_CATALOG: ReportCatalogEntry[] = [
  // ── EXECUTIVE (10) ──────────────────────────────────────────────────────────
  { id: 'EXE001', name: 'Executive Monthly Business Review', module: 'executive', type: 'executive_monthly_review', description: 'Comprehensive monthly overview of payment business KPIs, revenue, and performance trends for executive leadership.', formats: ['pdf','excel'], defaultSchedule: '0 6 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'EXE002', name: 'Board Performance Pack', module: 'executive', type: 'board_performance_pack', description: 'Board-level dashboard pack with strategic KPIs, risk summary, and regulatory status.', formats: ['pdf'], defaultSchedule: '0 7 1 * *', parameters: ['dateFrom','dateTo','quarter'] },
  { id: 'EXE003', name: 'Quarterly Business Review', module: 'executive', type: 'quarterly_business_review', description: 'Quarterly performance analysis with YoY comparison, growth trends, and strategic highlights.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 1,4,7,10 *', parameters: ['quarter','year'] },
  { id: 'EXE004', name: 'Revenue Performance Report', module: 'executive', type: 'revenue_performance', description: 'Detailed revenue breakdown by product, channel, and participant with margin analysis.', formats: ['pdf','excel','csv'], defaultSchedule: '0 6 * * 1', parameters: ['dateFrom','dateTo'] },
  { id: 'EXE005', name: 'Bank Performance Scorecard', module: 'executive', type: 'bank_performance_scorecard', description: 'Comparative scorecard of bank performance across clearing, settlement, cards, and compliance.', formats: ['pdf','excel'], defaultSchedule: '0 7 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'EXE006', name: 'Executive KPI Summary', module: 'executive', type: 'executive_kpi_summary', description: 'Single-page KPI summary with traffic light indicators for rapid executive consumption.', formats: ['pdf'], defaultSchedule: '0 7 * * 1', parameters: ['dateFrom','dateTo'] },
  { id: 'EXE007', name: 'Annual Report', module: 'executive', type: 'annual_report', description: 'Full annual performance report with year-in-review, charts, and forward-looking indicators.', formats: ['pdf'], defaultSchedule: '0 8 1 1 *', parameters: ['year'] },
  { id: 'EXE008', name: 'Investor Summary', module: 'executive', type: 'investor_summary', description: 'Investor-focused summary of financial performance, market position, and growth metrics.', formats: ['pdf'], parameters: ['dateFrom','dateTo','quarter'] },
  { id: 'EXE009', name: 'Strategic Performance Report', module: 'executive', type: 'strategic_performance', description: 'Strategic objectives tracking against KPIs with initiative progress and risk assessment.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'EXE010', name: 'Management Information Report', module: 'executive', type: 'management_information', description: 'Comprehensive MIS covering all business lines with drill-down capabilities.', formats: ['pdf','excel','csv'], defaultSchedule: '0 6 * * 1', parameters: ['dateFrom','dateTo'] },

  // ── CLEARING (15) ───────────────────────────────────────────────────────────
  { id: 'CLR001', name: 'Daily Clearing Report', module: 'clearing', type: 'daily_clearing', description: 'End-of-day clearing summary with volume, value, success rates, and exceptions.', formats: ['pdf','excel','csv'], defaultSchedule: '0 23 * * *', parameters: ['date'] },
  { id: 'CLR002', name: 'Hourly Clearing Report', module: 'clearing', type: 'hourly_clearing', description: 'Hour-by-hour clearing throughput analysis with peak period identification.', formats: ['pdf','excel'], defaultSchedule: '0 */1 * * *', parameters: ['date'] },
  { id: 'CLR003', name: 'Participant Clearing Report', module: 'clearing', type: 'participant_clearing', description: 'Per-participant clearing performance including volume, value, and success rates.', formats: ['pdf','excel','csv'], defaultSchedule: '0 6 * * *', parameters: ['dateFrom','dateTo','participantCode'] },
  { id: 'CLR004', name: 'Failed Transaction Analysis', module: 'clearing', type: 'failed_transaction_analysis', description: 'Root cause analysis of failed clearing transactions by error code, channel, and participant.', formats: ['pdf','excel'], defaultSchedule: '0 8 * * *', parameters: ['dateFrom','dateTo'] },
  { id: 'CLR005', name: 'Exception Management Report', module: 'clearing', type: 'exception_management', description: 'Clearing exceptions requiring manual intervention with aging and resolution tracking.', formats: ['pdf','excel','csv'], defaultSchedule: '0 9 * * *', parameters: ['dateFrom','dateTo'] },
  { id: 'CLR006', name: 'Interchange Fee Report', module: 'clearing', type: 'interchange_fee', description: 'Interchange fees collected and paid by participant with revenue breakdown.', formats: ['pdf','excel','csv'], defaultSchedule: '0 7 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'CLR007', name: 'Volume and Value Report', module: 'clearing', type: 'volume_value', description: 'Transaction volume and value trends with currency breakdown and growth analysis.', formats: ['pdf','excel','csv'], defaultSchedule: '0 6 * * 1', parameters: ['dateFrom','dateTo','currency'] },
  { id: 'CLR008', name: 'Scheme Participant Report', module: 'clearing', type: 'scheme_participant_clearing', description: 'Scheme-level participant clearing statistics for regulatory and operational reporting.', formats: ['pdf','excel'], defaultSchedule: '0 7 * * *', parameters: ['dateFrom','dateTo'] },
  { id: 'CLR009', name: 'Clearing Reconciliation Report', module: 'clearing', type: 'clearing_reconciliation', description: 'Clearing-to-settlement reconciliation with break identification and resolution status.', formats: ['pdf','excel'], defaultSchedule: '0 22 * * *', parameters: ['date'] },
  { id: 'CLR010', name: 'Inbound Clearing Report', module: 'clearing', type: 'inbound_clearing', description: 'Inbound clearing transactions analysis with source bank breakdown.', formats: ['pdf','excel','csv'], defaultSchedule: '0 7 * * *', parameters: ['dateFrom','dateTo'] },
  { id: 'CLR011', name: 'Outbound Clearing Report', module: 'clearing', type: 'outbound_clearing', description: 'Outbound clearing transactions analysis with destination bank breakdown.', formats: ['pdf','excel','csv'], defaultSchedule: '0 7 * * *', parameters: ['dateFrom','dateTo'] },
  { id: 'CLR012', name: 'Cross-Border Clearing Report', module: 'clearing', type: 'cross_border_clearing', description: 'International clearing transactions with currency, country, and correspondent bank analysis.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'CLR013', name: 'Peak Period Analysis', module: 'clearing', type: 'peak_period_analysis', description: 'Intraday and intraweek peak period analysis for capacity planning.', formats: ['pdf','excel'], parameters: ['dateFrom','dateTo'] },
  { id: 'CLR014', name: 'SLA Compliance Report', module: 'clearing', type: 'clearing_sla', description: 'Clearing SLA performance against agreed thresholds with breach analysis.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'CLR015', name: 'Clearing Performance Benchmark', module: 'clearing', type: 'clearing_benchmark', description: 'Performance benchmarking against industry standards and historical trends.', formats: ['pdf','excel'], parameters: ['dateFrom','dateTo'] },

  // ── SETTLEMENT (12) ─────────────────────────────────────────────────────────
  { id: 'SET001', name: 'Settlement Reconciliation Report', module: 'settlement', type: 'settlement_reconciliation', description: 'Daily settlement reconciliation with participant net positions and break analysis.', formats: ['pdf','excel','csv'], defaultSchedule: '0 23 * * *', parameters: ['date'] },
  { id: 'SET002', name: 'Settlement Position Report', module: 'settlement', type: 'settlement_position', description: 'Real-time and end-of-day settlement positions by participant and currency.', formats: ['pdf','excel'], defaultSchedule: '0 */4 * * *', parameters: ['date','currency'] },
  { id: 'SET003', name: 'Net Settlement Report', module: 'settlement', type: 'net_settlement', description: 'Net settlement amounts by participant after netting and offset calculations.', formats: ['pdf','excel','csv'], defaultSchedule: '0 22 * * *', parameters: ['date'] },
  { id: 'SET004', name: 'Liquidity Report', module: 'settlement', type: 'liquidity', description: 'Intraday liquidity positions, funding requirements, and stress indicators.', formats: ['pdf','excel'], defaultSchedule: '0 */2 * * *', parameters: ['date','currency'] },
  { id: 'SET005', name: 'Funding Requirement Report', module: 'settlement', type: 'funding_requirement', description: 'Next-day and intraday funding requirements with prefunding analysis.', formats: ['pdf','excel'], defaultSchedule: '0 18 * * *', parameters: ['date'] },
  { id: 'SET006', name: 'Settlement Exception Report', module: 'settlement', type: 'settlement_exception', description: 'Failed and exceptional settlement items with aging and resolution tracking.', formats: ['pdf','excel','csv'], defaultSchedule: '0 9 * * *', parameters: ['dateFrom','dateTo'] },
  { id: 'SET007', name: 'Treasury Operations Report', module: 'settlement', type: 'treasury_operations', description: 'Comprehensive treasury view of settlement flows, nostro positions, and FX exposure.', formats: ['pdf','excel'], defaultSchedule: '0 8 * * *', parameters: ['date'] },
  { id: 'SET008', name: 'End-of-Day Settlement Report', module: 'settlement', type: 'eod_settlement', description: 'Complete end-of-day settlement summary for regulatory and audit purposes.', formats: ['pdf','excel'], defaultSchedule: '0 23 * * *', parameters: ['date'] },
  { id: 'SET009', name: 'Intraday Settlement Report', module: 'settlement', type: 'intraday_settlement', description: 'Intraday settlement cycles with funding status and position updates.', formats: ['pdf','excel'], defaultSchedule: '0 */2 * * *', parameters: ['date'] },
  { id: 'SET010', name: 'Multi-Currency Settlement Report', module: 'settlement', type: 'multi_currency_settlement', description: 'Settlement positions across multiple currencies with FX conversion analysis.', formats: ['pdf','excel'], defaultSchedule: '0 23 * * *', parameters: ['date'] },
  { id: 'SET011', name: 'Deferred Settlement Report', module: 'settlement', type: 'deferred_settlement', description: 'Deferred and pending settlement items with expected settlement dates.', formats: ['pdf','excel','csv'], defaultSchedule: '0 8 * * *', parameters: ['dateFrom','dateTo'] },
  { id: 'SET012', name: 'Settlement Audit Report', module: 'settlement', type: 'settlement_audit', description: 'Complete audit trail of settlement activities for compliance and oversight.', formats: ['pdf','excel'], parameters: ['dateFrom','dateTo'] },

  // ── ACCOUNTS (10) ───────────────────────────────────────────────────────────
  { id: 'ACC001', name: 'Account Balance Report', module: 'accounts', type: 'account_balance', description: 'Current and historical account balances by account type and currency.', formats: ['pdf','excel','csv'], defaultSchedule: '0 6 * * *', parameters: ['date','accountType'] },
  { id: 'ACC002', name: 'Account Activity Report', module: 'accounts', type: 'account_activity', description: 'Detailed transaction activity per account with debit/credit analysis.', formats: ['pdf','excel','csv'], defaultSchedule: '0 6 * * *', parameters: ['dateFrom','dateTo','accountId'] },
  { id: 'ACC003', name: 'Dormancy Report', module: 'accounts', type: 'dormancy', description: 'Dormant accounts analysis with aging, balance summary, and regulatory compliance.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 * *', parameters: ['thresholdDays'] },
  { id: 'ACC004', name: 'Account Reconciliation Report', module: 'accounts', type: 'account_reconciliation', description: 'Account-level reconciliation between core banking and payment system.', formats: ['pdf','excel'], defaultSchedule: '0 22 * * *', parameters: ['date'] },
  { id: 'ACC005', name: 'Customer Account Summary', module: 'accounts', type: 'customer_account_summary', description: 'Customer-level summary of all accounts, balances, and recent activity.', formats: ['pdf','excel'], parameters: ['customerId','dateFrom','dateTo'] },
  { id: 'ACC006', name: 'Account Exception Report', module: 'accounts', type: 'account_exception', description: 'Accounts with anomalies, overdrafts, or status exceptions requiring attention.', formats: ['pdf','excel','csv'], defaultSchedule: '0 8 * * *', parameters: ['date'] },
  { id: 'ACC007', name: 'Account Audit Report', module: 'accounts', type: 'account_audit', description: 'Complete audit trail of account changes for compliance purposes.', formats: ['pdf','excel'], parameters: ['dateFrom','dateTo','accountId'] },
  { id: 'ACC008', name: 'New Account Report', module: 'accounts', type: 'new_account', description: 'Newly opened accounts with KYC status, initial funding, and onboarding metrics.', formats: ['pdf','excel','csv'], defaultSchedule: '0 7 * * *', parameters: ['dateFrom','dateTo'] },
  { id: 'ACC009', name: 'Account Closure Report', module: 'accounts', type: 'account_closure', description: 'Closed accounts with closure reason, residual balance handling, and compliance sign-off.', formats: ['pdf','excel'], defaultSchedule: '0 7 * * *', parameters: ['dateFrom','dateTo'] },
  { id: 'ACC010', name: 'Account Aging Report', module: 'accounts', type: 'account_aging', description: 'Account aging analysis based on last activity date with dormancy risk scoring.', formats: ['pdf','excel','csv'], defaultSchedule: '0 8 1 * *', parameters: [] },

  // ── CARDS (15) ──────────────────────────────────────────────────────────────
  { id: 'CRD001', name: 'Card Portfolio Report', module: 'cards', type: 'card_portfolio', description: 'Complete card portfolio overview: active, inactive, expired cards by type and brand.', formats: ['pdf','excel'], defaultSchedule: '0 7 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'CRD002', name: 'Card Spend Analysis', module: 'cards', type: 'card_spend_analysis', description: 'Detailed spend analysis by category, merchant, geography, and time.', formats: ['pdf','excel','csv'], defaultSchedule: '0 7 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'CRD003', name: 'Authorization Report', module: 'cards', type: 'authorization', description: 'Authorization performance with approval rates, response times, and decline analysis.', formats: ['pdf','excel'], defaultSchedule: '0 7 * * *', parameters: ['dateFrom','dateTo'] },
  { id: 'CRD004', name: 'Decline Analysis Report', module: 'cards', type: 'decline_analysis', description: 'Declined transaction analysis by reason code, merchant category, and channel.', formats: ['pdf','excel'], defaultSchedule: '0 8 * * *', parameters: ['dateFrom','dateTo'] },
  { id: 'CRD005', name: 'Chargeback Report', module: 'cards', type: 'chargeback', description: 'Chargeback cases with merchant breakdown, reason codes, and resolution status.', formats: ['pdf','excel','csv'], defaultSchedule: '0 8 * * 1', parameters: ['dateFrom','dateTo'] },
  { id: 'CRD006', name: 'Merchant Performance Report', module: 'cards', type: 'merchant_performance', description: 'Top merchants by spend, transaction count, and average ticket size.', formats: ['pdf','excel'], defaultSchedule: '0 7 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'CRD007', name: 'Card Lifecycle Report', module: 'cards', type: 'card_lifecycle', description: 'Cards by lifecycle stage: issued, activated, used, expiring, blocked, cancelled.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'CRD008', name: 'Card Utilization Report', module: 'cards', type: 'card_utilization', description: 'Card spend utilization vs. limits with dormancy and high-usage analysis.', formats: ['pdf','excel'], defaultSchedule: '0 7 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'CRD009', name: 'Interchange Revenue Report', module: 'cards', type: 'card_interchange_revenue', description: 'Interchange revenue from card transactions by merchant category and brand.', formats: ['pdf','excel','csv'], defaultSchedule: '0 7 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'CRD010', name: 'Card Fraud Report', module: 'cards', type: 'card_fraud', description: 'Card-related fraud cases with type, channel, and merchant analysis.', formats: ['pdf','excel'], defaultSchedule: '0 8 * * 1', parameters: ['dateFrom','dateTo'] },
  { id: 'CRD011', name: 'Premium Card Report', module: 'cards', type: 'premium_card', description: 'Premium and high-value card spending patterns and benefit utilization.', formats: ['pdf','excel'], defaultSchedule: '0 7 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'CRD012', name: 'Contactless Usage Report', module: 'cards', type: 'contactless_usage', description: 'Contactless payment adoption and usage trends by geography and merchant type.', formats: ['pdf','excel'], defaultSchedule: '0 7 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'CRD013', name: 'Digital Wallet Report', module: 'cards', type: 'digital_wallet', description: 'Digital wallet (Apple Pay, Google Pay) tokenization and usage statistics.', formats: ['pdf','excel'], defaultSchedule: '0 7 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'CRD014', name: 'International Spend Report', module: 'cards', type: 'international_spend', description: 'Cross-border card spend by country with FX and merchant category analysis.', formats: ['pdf','excel'], defaultSchedule: '0 7 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'CRD015', name: 'Card Renewal Report', module: 'cards', type: 'card_renewal', description: 'Cards approaching expiry with renewal status and customer notification tracking.', formats: ['pdf','excel','csv'], defaultSchedule: '0 8 1 * *', parameters: [] },

  // ── FRAUD (12) ──────────────────────────────────────────────────────────────
  { id: 'FRD001', name: 'Fraud Monitoring Report', module: 'fraud', type: 'fraud_monitoring', description: 'Real-time fraud monitoring summary with alert counts, amounts, and trends.', formats: ['pdf','excel'], defaultSchedule: '0 7 * * *', parameters: ['dateFrom','dateTo'] },
  { id: 'FRD002', name: 'Fraud Loss Report', module: 'fraud', type: 'fraud_loss', description: 'Fraud losses by type, channel, and merchant with recovery analysis.', formats: ['pdf','excel','csv'], defaultSchedule: '0 7 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'FRD003', name: 'Merchant Risk Report', module: 'fraud', type: 'merchant_risk', description: 'High-risk merchant analysis with fraud rates, chargebacks, and risk scores.', formats: ['pdf','excel'], defaultSchedule: '0 8 * * 1', parameters: ['dateFrom','dateTo'] },
  { id: 'FRD004', name: 'Suspicious Transaction Report', module: 'fraud', type: 'suspicious_transaction', description: 'Flagged transactions with risk scores and fraud indicators for investigator review.', formats: ['pdf','excel','csv'], defaultSchedule: '0 7 * * *', parameters: ['dateFrom','dateTo'] },
  { id: 'FRD005', name: 'Chargeback Fraud Report', module: 'fraud', type: 'chargeback_fraud', description: 'Fraud-related chargebacks with merchant and cardholder dispute analysis.', formats: ['pdf','excel'], defaultSchedule: '0 8 * * 1', parameters: ['dateFrom','dateTo'] },
  { id: 'FRD006', name: 'Fraud Investigation Report', module: 'fraud', type: 'fraud_investigation', description: 'Open and closed fraud investigations with evidence, decisions, and timelines.', formats: ['pdf','excel'], parameters: ['dateFrom','dateTo','status'] },
  { id: 'FRD007', name: 'Fraud Recovery Report', module: 'fraud', type: 'fraud_recovery', description: 'Recovery actions and outcomes with amounts recovered and recovery rates.', formats: ['pdf','excel'], defaultSchedule: '0 7 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'FRD008', name: 'False Positive Analysis', module: 'fraud', type: 'false_positive_analysis', description: 'False positive rates by detection model, rule, and merchant with tuning recommendations.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'FRD009', name: 'Fraud Channel Analysis', module: 'fraud', type: 'fraud_channel', description: 'Fraud breakdown by payment channel (online, POS, ATM, mobile) with trends.', formats: ['pdf','excel'], defaultSchedule: '0 7 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'FRD010', name: 'Geographic Fraud Report', module: 'fraud', type: 'geographic_fraud', description: 'Fraud cases by country, region, and city with heatmap visualization.', formats: ['pdf','excel'], defaultSchedule: '0 7 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'FRD011', name: 'Fraud Type Breakdown', module: 'fraud', type: 'fraud_type_breakdown', description: 'Fraud cases by type with trend analysis and emerging pattern identification.', formats: ['pdf','excel'], defaultSchedule: '0 7 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'FRD012', name: 'Year-on-Year Fraud Trend', module: 'fraud', type: 'fraud_yoy_trend', description: 'Multi-year fraud trend analysis with seasonal patterns and benchmark comparison.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 1 *', parameters: ['years'] },

  // ── AML (12) ────────────────────────────────────────────────────────────────
  { id: 'AML001', name: 'AML Alert Report', module: 'aml', type: 'aml_alert', description: 'AML alert summary with risk levels, assignment status, and SLA compliance.', formats: ['pdf','excel'], defaultSchedule: '0 7 * * *', parameters: ['dateFrom','dateTo'] },
  { id: 'AML002', name: 'High Risk Customer Report', module: 'aml', type: 'high_risk_customer', description: 'High and critical risk customers with alert history and action status.', formats: ['pdf','excel'], defaultSchedule: '0 7 * * 1', parameters: ['riskLevel'] },
  { id: 'AML003', name: 'Suspicious Activity Report (SAR)', module: 'aml', type: 'sar', description: 'SAR filings with case details, regulatory references, and filing confirmation.', formats: ['pdf'], parameters: ['dateFrom','dateTo'] },
  { id: 'AML004', name: 'Case Investigation Report', module: 'aml', type: 'aml_case_investigation', description: 'Open and closed AML case investigations with evidence, findings, and decisions.', formats: ['pdf','excel'], parameters: ['dateFrom','dateTo','status'] },
  { id: 'AML005', name: 'Sanctions Screening Report', module: 'aml', type: 'sanctions_screening', description: 'Sanctions screening results with hits, match scores, and disposition decisions.', formats: ['pdf','excel'], defaultSchedule: '0 8 * * *', parameters: ['dateFrom','dateTo'] },
  { id: 'AML006', name: 'PEP Monitoring Report', module: 'aml', type: 'pep_monitoring', description: 'Politically Exposed Persons monitoring with transaction activity and risk assessment.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'AML007', name: 'AML Compliance Summary', module: 'aml', type: 'aml_compliance_summary', description: 'AML program compliance overview for board and regulatory reporting.', formats: ['pdf'], defaultSchedule: '0 8 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'AML008', name: 'Transaction Monitoring Report', module: 'aml', type: 'transaction_monitoring', description: 'Transaction monitoring alert volumes, typologies, and tuning effectiveness.', formats: ['pdf','excel'], defaultSchedule: '0 7 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'AML009', name: 'KYC Refresh Report', module: 'aml', type: 'kyc_refresh', description: 'KYC refresh status by risk segment with overdue and upcoming renewals.', formats: ['pdf','excel','csv'], defaultSchedule: '0 8 1 * *', parameters: [] },
  { id: 'AML010', name: 'Correspondent Banking Report', module: 'aml', type: 'correspondent_banking', description: 'Correspondent banking relationships with risk ratings and due diligence status.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 */3 *', parameters: ['dateFrom','dateTo'] },
  { id: 'AML011', name: 'Beneficial Ownership Report', module: 'aml', type: 'beneficial_ownership', description: 'Beneficial ownership disclosure status and UBO verification completeness.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 */6 *', parameters: [] },
  { id: 'AML012', name: 'AML Risk Assessment', module: 'aml', type: 'aml_risk_assessment', description: 'Enterprise-wide AML risk assessment with inherent risk, controls, and residual risk ratings.', formats: ['pdf','excel'], parameters: ['assessmentDate'] },

  // ── COMPLIANCE (10) ─────────────────────────────────────────────────────────
  { id: 'CMP001', name: 'Compliance Status Report', module: 'compliance', type: 'compliance_status', description: 'Current compliance posture with finding status, severity distribution, and score.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 * *', parameters: [] },
  { id: 'CMP002', name: 'Audit Findings Report', module: 'compliance', type: 'audit_findings', description: 'Internal and external audit findings with remediation status and timelines.', formats: ['pdf','excel'], parameters: ['dateFrom','dateTo','status'] },
  { id: 'CMP003', name: 'Regulatory Submission Report', module: 'compliance', type: 'regulatory_submission', description: 'Regulatory reporting submissions with deadlines, status, and confirmation receipts.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'CMP004', name: 'Control Effectiveness Report', module: 'compliance', type: 'control_effectiveness', description: 'Control testing results with effectiveness ratings and improvement recommendations.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 */3 *', parameters: ['dateFrom','dateTo'] },
  { id: 'CMP005', name: 'Risk and Compliance Summary', module: 'compliance', type: 'risk_compliance_summary', description: 'Combined risk and compliance executive summary for board and audit committee.', formats: ['pdf'], defaultSchedule: '0 8 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'CMP006', name: 'Policy Compliance Report', module: 'compliance', type: 'policy_compliance', description: 'Policy compliance status with exceptions, waivers, and policy adherence metrics.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 * *', parameters: [] },
  { id: 'CMP007', name: 'Data Governance Report', module: 'compliance', type: 'data_governance', description: 'Data governance compliance including data quality, lineage, and privacy posture.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'CMP008', name: 'Regulatory Change Impact', module: 'compliance', type: 'regulatory_change_impact', description: 'Impact assessment of upcoming regulatory changes on operations and systems.', formats: ['pdf','excel'], parameters: ['effectiveDate'] },
  { id: 'CMP009', name: 'Breach Notification Report', module: 'compliance', type: 'breach_notification', description: 'Compliance breaches with regulatory notification status and remediation tracking.', formats: ['pdf'], parameters: ['dateFrom','dateTo'] },
  { id: 'CMP010', name: 'Compliance Calendar', module: 'compliance', type: 'compliance_calendar', description: 'Regulatory deadlines, audit schedules, and reporting calendar for the period.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 * *', parameters: ['year','month'] },

  // ── DOMESTIC SCHEME (12) ────────────────────────────────────────────────────
  { id: 'SCH001', name: 'Scheme Performance Report', module: 'scheme', type: 'scheme_performance', description: 'Overall domestic scheme performance with volume, value, and SLA metrics.', formats: ['pdf','excel'], defaultSchedule: '0 7 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'SCH002', name: 'Participant Performance Report', module: 'scheme', type: 'participant_performance', description: 'Per-participant scheme performance rankings with SLA compliance and volumes.', formats: ['pdf','excel'], defaultSchedule: '0 7 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'SCH003', name: 'SLA Compliance Report', module: 'scheme', type: 'scheme_sla', description: 'Scheme SLA compliance by participant with breach analysis and penalties.', formats: ['pdf','excel','csv'], defaultSchedule: '0 8 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'SCH004', name: 'Scheme Interchange Fee Report', module: 'scheme', type: 'scheme_interchange', description: 'Interchange fees by participant, product type, and merchant category.', formats: ['pdf','excel','csv'], defaultSchedule: '0 7 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'SCH005', name: 'Settlement Performance Report', module: 'scheme', type: 'scheme_settlement_performance', description: 'Scheme settlement performance with success rates and exception analysis.', formats: ['pdf','excel'], defaultSchedule: '0 23 * * *', parameters: ['date'] },
  { id: 'SCH006', name: 'Scheme Revenue Report', module: 'scheme', type: 'scheme_revenue', description: 'Scheme revenue from fees, penalties, and services by participant.', formats: ['pdf','excel'], defaultSchedule: '0 7 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'SCH007', name: 'Operational Performance Report', module: 'scheme', type: 'scheme_operational', description: 'Scheme operational metrics: uptime, throughput, latency, and incident count.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'SCH008', name: 'Exception Analysis Report', module: 'scheme', type: 'scheme_exception', description: 'Scheme-level exceptions and disputes with resolution status.', formats: ['pdf','excel','csv'], defaultSchedule: '0 8 * * 1', parameters: ['dateFrom','dateTo'] },
  { id: 'SCH009', name: 'Scheme Growth Report', module: 'scheme', type: 'scheme_growth', description: 'Participant onboarding, volume growth, and market share trends.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 */3 *', parameters: ['dateFrom','dateTo'] },
  { id: 'SCH010', name: 'Participant Onboarding Report', module: 'scheme', type: 'participant_onboarding', description: 'New participant onboarding status, milestones, and go-live readiness.', formats: ['pdf','excel'], parameters: ['dateFrom','dateTo'] },
  { id: 'SCH011', name: 'Scheme Rules Compliance', module: 'scheme', type: 'scheme_rules_compliance', description: 'Participant compliance with scheme rules and standards with breach tracking.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'SCH012', name: 'Scheme Benchmarking Report', module: 'scheme', type: 'scheme_benchmark', description: 'Scheme performance benchmarking against regional and international peers.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 */6 *', parameters: ['year'] },

  // ── RECONCILIATION (10) ─────────────────────────────────────────────────────
  { id: 'REC001', name: 'Daily Reconciliation Report', module: 'reconciliation', type: 'daily_reconciliation', description: 'End-of-day reconciliation status with match rates and break summary.', formats: ['pdf','excel','csv'], defaultSchedule: '0 23 * * *', parameters: ['date'] },
  { id: 'REC002', name: 'Unmatched Transaction Report', module: 'reconciliation', type: 'unmatched_transaction', description: 'Unmatched transactions requiring investigation with aging and variance amounts.', formats: ['pdf','excel','csv'], defaultSchedule: '0 8 * * *', parameters: ['dateFrom','dateTo'] },
  { id: 'REC003', name: 'Break Analysis Report', module: 'reconciliation', type: 'break_analysis', description: 'Reconciliation break analysis by system, type, and amount with root cause.', formats: ['pdf','excel'], defaultSchedule: '0 9 * * *', parameters: ['dateFrom','dateTo'] },
  { id: 'REC004', name: 'Aging Report', module: 'reconciliation', type: 'recon_aging', description: 'Aged reconciliation items by bucket with escalation recommendations.', formats: ['pdf','excel','csv'], defaultSchedule: '0 8 * * 1', parameters: [] },
  { id: 'REC005', name: 'Reconciliation Status Report', module: 'reconciliation', type: 'reconciliation_status', description: 'Current reconciliation status across all system pairs with completeness metrics.', formats: ['pdf','excel'], defaultSchedule: '0 */2 * * *', parameters: ['date'] },
  { id: 'REC006', name: 'Financial Reconciliation Summary', module: 'reconciliation', type: 'financial_reconciliation_summary', description: 'Finance-focused reconciliation summary for month-end close and sign-off.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 * *', parameters: ['month','year'] },
  { id: 'REC007', name: 'Nostro Reconciliation Report', module: 'reconciliation', type: 'nostro_reconciliation', description: 'Nostro account reconciliation with correspondent bank statements.', formats: ['pdf','excel'], defaultSchedule: '0 22 * * *', parameters: ['date','currency'] },
  { id: 'REC008', name: 'Card Reconciliation Report', module: 'reconciliation', type: 'card_reconciliation', description: 'Card transaction reconciliation between issuer, acquirer, and scheme.', formats: ['pdf','excel','csv'], defaultSchedule: '0 22 * * *', parameters: ['date'] },
  { id: 'REC009', name: 'Clearing Reconciliation Report', module: 'reconciliation', type: 'clearing_recon_detail', description: 'Detailed clearing-to-settlement reconciliation with item-level matching.', formats: ['pdf','excel','csv'], defaultSchedule: '0 23 * * *', parameters: ['date'] },
  { id: 'REC010', name: 'Month-End Reconciliation', module: 'reconciliation', type: 'month_end_reconciliation', description: 'Comprehensive month-end reconciliation pack for finance close.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 * *', parameters: ['month','year'] },

  // ── FINANCE (12) ────────────────────────────────────────────────────────────
  { id: 'FIN001', name: 'Revenue Report', module: 'finance', type: 'revenue', description: 'Revenue breakdown by product, channel, and participant with trend analysis.', formats: ['pdf','excel','csv'], defaultSchedule: '0 7 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'FIN002', name: 'Profitability Report', module: 'finance', type: 'profitability', description: 'Profitability analysis by business unit, product, and customer segment.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'FIN003', name: 'Fee Income Report', module: 'finance', type: 'fee_income', description: 'Fee income by type: interchange, processing, service fees, and penalties.', formats: ['pdf','excel','csv'], defaultSchedule: '0 7 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'FIN004', name: 'Cost Analysis Report', module: 'finance', type: 'cost_analysis', description: 'Operating cost analysis by category with efficiency ratios and benchmarks.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'FIN005', name: 'Business Unit Profitability', module: 'finance', type: 'bu_profitability', description: 'Profitability by business unit with cost allocation and contribution margins.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'FIN006', name: 'Bank Profitability Scorecard', module: 'finance', type: 'bank_profitability_scorecard', description: 'Per-bank profitability with revenue, cost, margin, and growth metrics.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'FIN007', name: 'Interchange P&L Report', module: 'finance', type: 'interchange_pl', description: 'Interchange P&L by card type, merchant category, and network.', formats: ['pdf','excel'], defaultSchedule: '0 7 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'FIN008', name: 'Processing Cost Report', module: 'finance', type: 'processing_cost', description: 'Transaction processing costs per unit with volume discounts and efficiency analysis.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'FIN009', name: 'Budget vs Actual Report', module: 'finance', type: 'budget_vs_actual', description: 'Budget variance analysis with revenue and cost actuals vs. plan.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 * *', parameters: ['month','year'] },
  { id: 'FIN010', name: 'Margin Analysis Report', module: 'finance', type: 'margin_analysis', description: 'Net margin analysis by product and customer segment with trend visualization.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'FIN011', name: 'Revenue Forecast Report', module: 'finance', type: 'revenue_forecast', description: 'Revenue forecast with assumptions, scenarios, and sensitivity analysis.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 */3 *', parameters: ['forecastMonths'] },
  { id: 'FIN012', name: 'Annual Financial Summary', module: 'finance', type: 'annual_financial', description: 'Full-year financial summary with P&L, KPIs, and YoY comparisons.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 1 *', parameters: ['year'] },

  // ── OPERATIONS (10) ─────────────────────────────────────────────────────────
  { id: 'OPS001', name: 'Operations Health Report', module: 'operations', type: 'operations_health', description: 'System health overview with uptime, throughput, and incident summary.', formats: ['pdf','excel'], defaultSchedule: '0 7 * * *', parameters: ['dateFrom','dateTo'] },
  { id: 'OPS002', name: 'Incident Report', module: 'operations', type: 'incident', description: 'Incident log with severity, duration, impact, and resolution details.', formats: ['pdf','excel'], defaultSchedule: '0 8 * * 1', parameters: ['dateFrom','dateTo'] },
  { id: 'OPS003', name: 'Availability Report', module: 'operations', type: 'availability', description: 'System availability and uptime by component with SLA compliance.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'OPS004', name: 'Performance Report', module: 'operations', type: 'performance', description: 'Transaction processing performance with latency, throughput, and queue metrics.', formats: ['pdf','excel'], defaultSchedule: '0 7 * * *', parameters: ['dateFrom','dateTo'] },
  { id: 'OPS005', name: 'Transaction Processing Report', module: 'operations', type: 'transaction_processing', description: 'Detailed transaction processing metrics by channel, type, and time of day.', formats: ['pdf','excel','csv'], defaultSchedule: '0 7 * * *', parameters: ['dateFrom','dateTo'] },
  { id: 'OPS006', name: 'Capacity Planning Report', module: 'operations', type: 'capacity_planning', description: 'System capacity utilization with growth projections and upgrade recommendations.', formats: ['pdf','excel'], parameters: ['forecastMonths'] },
  { id: 'OPS007', name: 'SLA Performance Report', module: 'operations', type: 'sla_performance', description: 'SLA performance against all agreed metrics with breach and remedy tracking.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'OPS008', name: 'Change Management Report', module: 'operations', type: 'change_management', description: 'Change requests, deployments, and rollbacks with impact assessment.', formats: ['pdf','excel'], defaultSchedule: '0 8 * * 1', parameters: ['dateFrom','dateTo'] },
  { id: 'OPS009', name: 'Disaster Recovery Report', module: 'operations', type: 'disaster_recovery', description: 'DR test results, RTO/RPO metrics, and recovery capability assessment.', formats: ['pdf','excel'], parameters: ['testDate'] },
  { id: 'OPS010', name: 'Vendor Performance Report', module: 'operations', type: 'vendor_performance', description: 'Third-party and technology vendor performance against contractual obligations.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 * *', parameters: ['dateFrom','dateTo'] },

  // ── CUSTOMER ANALYTICS (10) ─────────────────────────────────────────────────
  { id: 'CUS001', name: 'Customer Segmentation Report', module: 'customer', type: 'customer_segmentation', description: 'Customer segmentation by transaction behaviour, value, and risk profile.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'CUS002', name: 'Customer Activity Report', module: 'customer', type: 'customer_activity', description: 'Customer transaction activity with frequency, recency, and monetary value.', formats: ['pdf','excel','csv'], defaultSchedule: '0 7 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'CUS003', name: 'Merchant Analysis Report', module: 'customer', type: 'merchant_analysis', description: 'Merchant performance and spend patterns with category and geographic breakdown.', formats: ['pdf','excel'], defaultSchedule: '0 7 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'CUS004', name: 'Customer Lifetime Value Report', module: 'customer', type: 'clv', description: 'CLV analysis with revenue contribution, retention, and profitability metrics.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'CUS005', name: 'Retention Report', module: 'customer', type: 'retention', description: 'Customer retention analysis with churn indicators and at-risk segment identification.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'CUS006', name: 'Acquisition Report', module: 'customer', type: 'acquisition', description: 'New customer acquisition trends with onboarding funnel and activation metrics.', formats: ['pdf','excel'], defaultSchedule: '0 7 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'CUS007', name: 'Customer Risk Profile', module: 'customer', type: 'customer_risk_profile', description: 'Customer risk distribution with fraud, credit, and AML risk scores.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 * *', parameters: ['riskLevel'] },
  { id: 'CUS008', name: 'Digital Adoption Report', module: 'customer', type: 'digital_adoption', description: 'Digital channel adoption rates with mobile, online, and contactless usage trends.', formats: ['pdf','excel'], defaultSchedule: '0 7 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'CUS009', name: 'Channel Usage Report', module: 'customer', type: 'channel_usage', description: 'Transaction channel mix: POS, ATM, online, mobile, contactless with trends.', formats: ['pdf','excel','csv'], defaultSchedule: '0 7 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'CUS010', name: 'Customer Satisfaction Report', module: 'customer', type: 'customer_satisfaction', description: 'NPS, CSAT, and CES scores with decline and dispute frequency as proxy metrics.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 * *', parameters: ['dateFrom','dateTo'] },

  // ── DATA PRODUCTS (10) ──────────────────────────────────────────────────────
  { id: 'DAT001', name: 'Data Product Inventory', module: 'data_products', type: 'data_product_inventory', description: 'Full inventory of data products with status, quality scores, and consumer counts.', formats: ['pdf','excel','csv'], defaultSchedule: '0 8 1 * *', parameters: [] },
  { id: 'DAT002', name: 'Data Quality Report', module: 'data_products', type: 'data_quality', description: 'Data quality metrics per product: completeness, accuracy, timeliness, consistency.', formats: ['pdf','excel'], defaultSchedule: '0 7 * * 1', parameters: ['dateFrom','dateTo'] },
  { id: 'DAT003', name: 'Access Audit Report', module: 'data_products', type: 'data_access_audit', description: 'Data product access requests, approvals, rejections, and active consumer list.', formats: ['pdf','excel','csv'], defaultSchedule: '0 8 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'DAT004', name: 'Lineage Report', module: 'data_products', type: 'data_lineage', description: 'Data lineage visualization and documentation for governance and compliance.', formats: ['pdf','excel'], parameters: ['productId'] },
  { id: 'DAT005', name: 'Data Usage Report', module: 'data_products', type: 'data_usage', description: 'API usage statistics per data product with consumer breakdown and query patterns.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'DAT006', name: 'Consumer Adoption Report', module: 'data_products', type: 'consumer_adoption', description: 'Data product consumer adoption trends with new users and active consumer metrics.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'DAT007', name: 'Data Freshness Report', module: 'data_products', type: 'data_freshness', description: 'Data freshness by product with last refresh timestamps and staleness alerts.', formats: ['pdf','excel','csv'], defaultSchedule: '0 7 * * *', parameters: [] },
  { id: 'DAT008', name: 'Schema Change Report', module: 'data_products', type: 'schema_change', description: 'Schema changes and breaking changes log with consumer impact assessment.', formats: ['pdf','excel'], defaultSchedule: '0 8 * * 1', parameters: ['dateFrom','dateTo'] },
  { id: 'DAT009', name: 'API Usage Report', module: 'data_products', type: 'api_usage', description: 'API call volume, latency, error rates, and usage by consumer and endpoint.', formats: ['pdf','excel'], defaultSchedule: '0 7 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'DAT010', name: 'Data Governance Summary', module: 'data_products', type: 'data_governance_summary', description: 'Data governance posture: ownership, quality, lineage, and access control coverage.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 * *', parameters: ['dateFrom','dateTo'] },

  // ── PLATFORM (10) ───────────────────────────────────────────────────────────
  { id: 'PLT001', name: 'User Activity Report', module: 'platform', type: 'user_activity', description: 'User login, feature usage, and session analytics by role and tenant.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'PLT002', name: 'Subscription Report', module: 'platform', type: 'subscription', description: 'Tenant subscription status, seat utilization, and renewal pipeline.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 * *', parameters: [] },
  { id: 'PLT003', name: 'Tenant Performance Report', module: 'platform', type: 'tenant_performance', description: 'Per-tenant platform performance with API usage, report generation, and activity.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'PLT004', name: 'License Utilization Report', module: 'platform', type: 'license_utilization', description: 'License utilization by tenant with over/under provisioning analysis.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 * *', parameters: [] },
  { id: 'PLT005', name: 'Audit Trail Report', module: 'platform', type: 'audit_trail', description: 'Complete user action audit trail for compliance and forensic investigation.', formats: ['pdf','excel','csv'], parameters: ['dateFrom','dateTo','userId'] },
  { id: 'PLT006', name: 'Security Audit Report', module: 'platform', type: 'security_audit', description: 'Security events, failed logins, permission changes, and anomalous access.', formats: ['pdf','excel'], defaultSchedule: '0 8 * * 1', parameters: ['dateFrom','dateTo'] },
  { id: 'PLT007', name: 'API Performance Report', module: 'platform', type: 'api_performance', description: 'Platform API performance: latency, error rates, and throughput by endpoint.', formats: ['pdf','excel'], defaultSchedule: '0 7 * * *', parameters: ['dateFrom','dateTo'] },
  { id: 'PLT008', name: 'Error Rate Report', module: 'platform', type: 'error_rate', description: 'Application error rates by module, endpoint, and severity with root cause analysis.', formats: ['pdf','excel'], defaultSchedule: '0 8 * * 1', parameters: ['dateFrom','dateTo'] },
  { id: 'PLT009', name: 'Adoption Metrics Report', module: 'platform', type: 'adoption_metrics', description: 'Feature adoption rates across dashboard, reports, marketplace, and builder.', formats: ['pdf','excel'], defaultSchedule: '0 8 1 * *', parameters: ['dateFrom','dateTo'] },
  { id: 'PLT010', name: 'System Utilization Report', module: 'platform', type: 'system_utilization', description: 'Infrastructure utilization: CPU, memory, storage, and network by service.', formats: ['pdf','excel'], defaultSchedule: '0 7 * * *', parameters: ['dateFrom','dateTo'] },
];
